title: "Analyse de communautés microbiennes"
description: "Analyse reproductible de communautés microbiennes basée sur Pagaling et al. (2017)"
author: "Tugdual DEVEAUD"

theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

lang: fr
timezone: Europe/Paris

# Navigation
header_pages:
  - index.md
  - analyse_article.md

# Plugins autorisés
plugins:
  - jekyll-seo-tag

# Exclusions
exclude:
  - "*.Rmd"
  - "*.Rproj"
  - ".Rhistory"
  - ".gitignore"
